const TYPES = {
  //CURRENT PROJECTS
  GET_PROJECTS: "GET_PROJECTS",
  GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
  GET_PROJECTS_ERROR: "GET_PROJECTS_ERROR",
  // CONTACT
  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_REQUEST_SUCCESS: ".ADD_CONTACT_REQUEST_SUCCESS",
  ADD_CONTACT_REQUEST_ERROR: ".ADD_CONTACT_REQUEST_ERROR",
  // REQUEST SUPPORT
  ADD_SUPPORT_REQUEST: "ADD_SUPPORT_REQUEST"
};
export default TYPES;
